name: Web API Deploy Pipeline
on: 
  push:
    paths:
      - 'github/workflows/**'
      - 'cicd-section/api/**'
#GithubActionsのジョブを定義
#cicd-section/api/の配下のディレクトリに変更があった場合のみ下記のjobを動かす

env:
  AWS_REGION: ap-northeast-1
  ECS_CLUSTER: ecs-demo-app-cluster
  ECS_SERVICE: my-app-api-service
  ECR_REPOSITORY: my-app-api
  ECS_TASK_DEFINITION: cicd-section/.aws/task-def-api.json
  #ECS_TASK_DEFINITIONタスク定義のJSONファイルのディスプレイパスを記入

permissions:
  id-token: write
  contents: read
#Configure AWS credentialsでのOpenID Connect (OIDC) プロバイダーを使用したIAMロールの前提条件

jobs:
#Test/Build
  test-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cicd-section/api
    steps:
      #Checkout code Checkoutv4を使用する
      - uses: actions/checkout@v4
      - name: Run Tests and Build an Image
        run: docker image build -t temp_api_image:latest .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker image tag temp_api_image:latest $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          docker image push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
#Deploy